#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }
login:
  path: /auth/login
  defaults:
    _controller:  App\Controller\AuthController:login

login_check:
  path: /login_check

logout:
  path: /logout